### ISSUE TITLE
Url shortener service

### ISSUE THREAD

**Issue by yukinotenshi** [yukinotenshi/pleb-services#1]
Create a simple web service for url shortening. Slug will consist of 5 random characters, preferably only lowercase letters + digits.

ORM : gorm.io
no need for a web framework

**Comment by ilmanzo** [comment]
Hello, I'd like to contribute on this issue. Can you assign it to me ?

**Comment by ridho9** [comment]
Ah sorry but actually this is my issue and the owner forgot to assign it to me
